name: opentf_kapnmt
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11.9
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - gensim
  - pytorch-cuda=11.8
  - pip
  - pip:
    - OpenNMT-py
    - torch-geometric
    - pytrec_eval
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
